### ISSUE TITLE
Try to install tangible landscape on ubuntu 18 ,  but failed

### ISSUE THREAD

**Issue by rengifoortega** [tangible-landscape/tangible-landscape-install#3]
hi guys
I am trying to install tangible landscape on Ubuntu 18 but it fails. I would appreciate any information or help you can give. it seems to be a dependencies issue

cheers

Rengifo

The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gdal-bin : Breaks: python-gdal (< 2.4.3~) but 2.2.3+dfsg-2 is to be installed
 liblas-bin : Depends: libgdal20 (>= 2.3.0) but it is not going to be installed
              Depends: libgeotiff2 (>= 1.3.0) but it is not going to be installed
              Depends: liblas-c3 (>= 1.8.0) but it is not going to be installed
              Depends: liblas3 (>= 1.8.1) but it is not going to be installed
 liblas-c-dev : Depends: liblas-c3 (= 1.8.1-8~bionic2) but it is not going to be installed
 liblas-dev : Depends: liblas3 (= 1.8.1-8~bionic2) but it is not going to be installed
 python-gdal : Depends: gdal-abi-2-2-3
               Depends: libgdal20 (>= 2.2.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by petrasovaa** [comment]
You may try to uninstall python-gdal and liblas-bin, these are optional dependencies. Does this happen when you run the install script or what is the context?

**Comment by rengifoortega** [comment]
Hi Anna !
Thank for your quick response.Yes, it occurs when I try t install using the script. By the way, when click on the direct link you created, I get error 404. So, what i did was to clone the repository  and run within the  tangiblelandscape  folder.
Best regards
Rengifo

**Comment by petrasovaa** [comment]
Which link?

**Comment by rengifoortega** [comment]
> Which link?

sorry for not been  more clear  Anna. Is this one. But I guess is not so relevant though.
![Screenshot from 2023-10-16 22-59-24](https://github.com/tangible-landscape/tangible-landscape-install/assets/98947748/d98f4984-83b8-4529-8e43-65c0ed1b0b90)

**Comment by rengifoortega** [comment]
I quite trying to install it on ubuntu 18. I will concentrate only on ubuntu 22.
